#!/bin/sh
#
# Copyright (c) 2018, Emerald Onion
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#  list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#  this list of conditions and the following disclaimer in the documentation
#  and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# Import common
. /usr/local/share/gibson/common

usage() {
	cat <<EOF
Usage: gibson [options] command [options]

Commands:
	command	-- Execute a command in specified jail(s)
	restart -- Restart Tor in the specified jail(s)
	start	-- Start Tor in the specified jail(s)
	stop	-- Stop Tor in the specified jail(s)
	update	-- Update jail OS
	upgrade -- Upgrade package(s) in the specified jail(s)
EOF
	exit 1
}

CMD_OPTS=""

while getopts ":v" OPTION; do
	case "${OPTION}" in
	v)
		CMD_OPTS="${CMD_OPTS} -v"
		;;
	*)
		usage
		;;
	esac
done

shift $((OPTIND-1))

[ $# -lt 1 ] && usage

CMD=$1
shift

if [ ! -x "/usr/local/share/gibson/${CMD}.sh" ]; then
	abort "Unknown command: ${CMD}"
fi

/usr/local/share/gibson/${CMD}.sh ${CMD_OPTS} $*





