#!/bin/sh
#
# Copyright (c) 2018, Emerald Onion
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#  list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#  this list of conditions and the following disclaimer in the documentation
#  and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# Import configuration provided by the user
if [ -f /usr/local/etc/gibson.conf ]; then
	. /usr/local/etc/gibson.conf
else
	(>&2 echo "gibson configuration file (/usr/local/etc/gibson.conf) missing")
	exit 1
fi

abort() {
	# Complain and then quit
	(>&2 echo "$1")
	echo
	usage
}

debug() {
	# Depending on our verbosity, print something (or not) 
	if [ ! -z "${VERBOSE}" ]; then
		(>&2 echo "$1")
	fi
}

gibson_os() {
	# We currently only distinguish between FreeBSD and HardenedBSD
	# We will add support for other systems soon
	case $(uname) in
	FreeBSD)
		# If we are HardenedBSD, we will have a hardening.version sysctl
		if sysctl hardening.version >/dev/null 2>&1; then
			echo "HardenedBSD"
		else
			echo "FreeBSD"
		fi
		;;
	*)
		echo "Unknown"
		;;
	esac
}
